name: Print commit history to file

on: push

jobs:
  print:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /
        
    steps:
    # Runs a single command using the runners shell
    - name: Print to file
      run: git log > CommitHistory.txt
